seed : 1

env : 
  num_envs : 100
  num_eval : 4
  env_engine : 'gym'  # gym  brax
  name : InvertedPendulum  # InvertedPendulum HalfCheetah-v4 inverted_pendulum halfcheetah
  eval_every : 5000
  episode_max_length : 1000
  

train :
  start_training_after_x_steps :  10_000
  total_train_step : 200_000
  max_replay_size : 10_000
  batch_size : 256
  grad_steps_per_step : 1
  with_scan : True
  agent : 
    _target_: agents.SAC
    critic_polyak_update_val : 0.001
    update_q_target_every : 1
    discount : 0.99
    critic_learning_rate : 0.001
    actor_learning_rate : 0.001
    target_entropy : 'auto'
    entropy_coeff :  0.01
    entropy_learning_rate : 0 # set to 0 to deactivate entropy coefficient learning. 
    max_grad_norm : 0.5
    critic_network : 
      hidden_layers : [256,256]
    actor_network: 
      hidden_layers : [64,64]

log:
  logger : 
    _target_ : agents.SACLogger
    mode : online
    group : SAC