seed : 3

env : 
  num_envs : 1
  num_eval : 10
  env_engine : 'gym'  # gym  brax
  name : InvertedPendulum-v4  # InvertedPendulum HalfCheetah-v4 inverted_pendulum halfcheetah
  eval_every : 500
  episode_max_length : 1000
  

train :
  start_training_after_x_steps :  100
  total_train_step : 20_000
  max_replay_size : 50_000
  batch_size : 64
  grad_steps_per_step : 1
  with_scan : True
  agent : 
    _target_: agents.SAC
    critic_polyak_update_val : 5e-3
    update_q_target_every : 1
    discount : 0.99
    critic_learning_rate : 1e-3
    actor_learning_rate : 1e-3
    target_entropy : 'auto'
    entropy_coeff :  1
    entropy_learning_rate : 1e-3 # set to 0 to deactivate entropy coefficient learning. 
    max_grad_norm : 0.5
    critic_network : 
      hidden_layers : [256,256]
    actor_network: 
      hidden_layers : [256,256]

log:
  logger : 
    _target_ : agents.SACLogger
    mode : online
    group : SAC